apiVersion: v1
kind: Pod
metadata:
  name: volume-ebs
spec:
  imagePullSecrets:
    - name: regcred
  nodeName: ip-172-31-101-245.ec2.internal
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: ebs-volume
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"  
  volumes:
  - name: ebs-volume
    # This AWS EBS volume must already exist.
    awsElasticBlockStore:
      volumeID: vol-0b4e04c91db8e0ce0
      fsType: ext4